### PR TITLE
Reprocessing instead of event replication

### PR DESCRIPTION
**Pull request by lenaschoenburg**

### CODE REVIEW

**Comment by lenaschoenburg** [comment]
I discussed this a little bit with @deepthidevaki who had a different idea which, on first glance, looked the the polar opposite of what I described here. To paraphrase, it was "make events really cheap to apply, no state lookup, only simple state modification".

Currently this is not the case but we came up with an interesting idea where the stream platform could **derive events** based on all state modifications done during (batch-) processing. These would be smaller and much cheaper to apply than the _semantic_ events produced by the engine.
I think this strikes a really nice compromise where we get similar benefits such as less data to write and replicate while also reducing state reads and completely circumventing problems of reprocessing such as increased risk of catastrophic bugs and difficult to manage upgrades.

**Comment by lenaschoenburg** [comment]
I tried to hack this together: https://github.com/camunda/zeebe/compare/os-derive-events?expand=1

It's extremely ~~elegant~~ cursed because it simply uses the serialized `WriteBatch` of the current RocksDB transaction to create an 'aggregated' event that is written instead of the usual events.
On replay, the current transaction is rebuilt from that `WriteBatch`. I have no idea if that is actually safe but so far RocksDb isn't complaining...

**Comment by npepinpe** [comment]
Writing down what we discussed earlier:

I think this is a great idea! To expand on this, we could already move towards this to make replaying extremely lightweight by using the write batch, while still keeping compatibility with the exporters/external applications.

With this idea, the events are now used purely for auditing. So let's introduce a new record type, AUDIT. To start us off, we could for now pack all the follow up event records into a big audit record. If the size of the audit record is an issue, we could still compress them, as events likely share a lot of the same data (e.g. the SBE template, probably some metadata, etc.).

This would greatly reduce the number of written records - it also provides an easy cut off point, i.e. if there are no exporters we can simply skip those records, since the replay state machine only uses the write batch diff.

So processing a batch will now result in: X follow commands, 1 write batch diff event record, and one audit record.

For backwards compatibility, we can unpack the audit record in the exporter director for now. This means we need to have some solution on what happens when only some of the events in an audit record are exported, but I'm sure we can figure this out (using, say, the audit record position + the offset in the event batch or something).

It would still be interesting to test and see the impact on Elastic ingestion if we did not unpack the record, but simply exported it as is :+1:

It's a really exciting idea, I wish I had some time to join you on prototyping it, great job!

**Comment by npepinpe** [comment]
What do you think about trying it out for the performance day next week? Or maybe you can't wait that long - don't wait on my account if you've got the itch :smile:

**Comment by lenaschoenburg** [comment]
@npepinpe That sounds good, I don't think I can get to it earlier anyway :+1:

**Pull request closed without merging**
