### PR TITLE
Collect changes for engine ZEP

### PR DESCRIPTION
**Pull request by ChrisKujawa**
Add notes for deployment changes, related to https://github.com/zeebe-io/zeebe/issues/6173 .

### CODE REVIEW

**Comment by npepinpe** [comment]
Introduced new record value type, ProcessEvent. See https://github.com/camunda-cloud/zeebe/issues/6737

**Comment by npepinpe** [comment]
Added `ProcessMessageSubscriptionIntent.DELETING` to represent a subscription closing's state.

**Comment by Zelldon** [comment]
@saig0 you mentioned you work on the ZEP are you incorporate these changes?

**Comment by korthout** [comment]
Thanks @remcowesterhoud

**Comment by saig0** [comment]
I'm closing this PR. The ZEP is implemented and there are minor changes compared to the reference documentation. But I don't see any value in updating this part. The code itself is the better documentation. 

The nice diagram of the deployment distribution is moved to the internal docs.

**Pull request closed without merging**
